id = "kv-lang-highlighting"
name = "Kivy Language Highlighting"
version = "0.0.1"
schema_version = 1
authors = ["RY34 <you@example.com>"]
description = "Basic Kivy Language Highlighting for Kivy: The Open Source Python App Development Framework."
repository = "https://github.com/RY34/zed-kvlang-highlighting.git"

[grammars.kvlang]
repository = "https://github.com/RY34/tree-sitter-kvlang.git"
rev = "a0642304b08eb1f14e32467d662117f23fcded2d"
