name = "Kivy lang"
grammar = "kvlang"
path_suffixes = ["kv"]
first_line_pattern = '#:kivy '
line_comments = ["#"]
tab_size = 4
hard_tabs = false
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
